export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "HIDE_ALERT";

export const SETUP_USER = "SETUP_USER";
export const SETUP_SUCCESS = "SETUP_SUCCESS";
export const SETUP_FAIL = "SETUP_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_JOB = "CREATE_JOB";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const CREATE_JOB_FAIL = "CREATE_JOB_FAIL";

export const GET_JOBS = "GET_JOBS";
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";

export const EDIT_JOBS = "EDIT_JOBS";

export const EDIT_JOBS_BEGINS = "EDIT_JOBS_BEGINS";
export const EDIT_JOBS_SUCCESS = "EDIT_JOBS_SUCCESS";
export const EDIT_JOBS_ERROR = "EDIT_JOBS_ERROR";

export const DELETE_JOBS = "DELETE_JOBS";
export const DELETE_JOBS_ERROR = "DELETE_JOBS_ERROR";

export const SHOW_STATS = "SHOW_STATS";
export const SHOW_STATS_SUCCESS = "SHOW_STATS_SUCCESS";

export const CLEAR_FILTERS = "CLEAR_FILTERS";

export const CHANGE_PAGE = "CHANGE_PAGE";
